# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isdn',
            new_name='isbn',
        ),
    ]
